### ISSUE TITLE
Ready for review

### ISSUE THREAD

**Issue by tswayd** [tswayd/analyzing_covid_mobility_dataset#3]
Please take a look. @melt6457 @mhaliz

**Comment by tswayd** [comment]
I forgot to make one extra figure of my choice. I will work on that right now.

**Comment by tswayd** [comment]
Ok everything should be ready for evaluation now thank you!

**Comment by naupaka** [comment]
Please fix issues #4 and #5 -- also please remember that your git commit messages should follow this style guide:

https://chris.beams.io/posts/git-commit/

Start with a capital letter, use imperative tense

**Comment by tswayd** [comment]
> Please fix issues #4 and #5 -- also please remember that your git commit messages should follow this style guide:
> 
> https://chris.beams.io/posts/git-commit/
> 
> Start with a capital letter, use imperative tense

Ok will do!

**Comment by tswayd** [comment]
I think issue 4 and 5 have now been resolved thank you.

**Comment by naupaka** [comment]
Looks good! Nice job.
