### ISSUE TITLE
Please be sure to lint all the files

### ISSUE THREAD

**Issue by naupaka** [tswayd/analyzing_covid_mobility_dataset#4]
There are some errors that need to be resolved.

You can use this `lintr::lint_dir(pattern = rex::rex(".", or("R", "r", "Rmd", "rmd"), end))`

**Comment by tswayd** [comment]
Hi professor I did that in the console and found no errors that needed to be resolved?

**Comment by naupaka** [comment]
I got errors that the last line of the file was incomplete

**Comment by naupaka** [comment]
https://github.com/jimhester/lintr/issues/327

**Comment by tswayd** [comment]
Oh woops sorry I was just ignoring the warning message my bad.
