### ISSUE TITLE
Remove unnecessary files

### ISSUE THREAD

**Issue by melt6457** [tswayd/analyzing_covid_mobility_dataset#8]
You have a couple of unnecessary files which you can simply remove. For each of these you can either `git rm` on your local machine or delete them on github. 

- [ ] output/.DS_Store
- [ ] data/.DS_Store
- [ ] raw_data/.DS_Store
- [ ] code/.DS_Store
- [ ] code/.Rapp.history

Once you have deleted the files you can make a couple of small changes to your .gitignore to keep them from coming back.

https://github.com/tswayd/analyzing_covid_mobility_dataset/blob/553f83e81c396d6eb1fbd8f56ed4ab3f662d2438/.gitignore#L5

to `*.DS_Store` which will make sure any .DS_Store file in the project is not pushed to github.

And also add this line to the end of your .gitignore `*.Rapp.history`

**Comment by tswayd** [comment]
Do I need to include the asterisk?

**Comment by tswayd** [comment]
I just did it both ways just in case.

**Comment by melt6457** [comment]
The asterisk is helpful because it is a wildcard and will make sure every file with that extension isn’t included. So you can explicitly list every file, but the wildcard is easier.
